server:
  port: 9999

spring:
  application:
    name: dennis-light-step-demo
  datasource:
    url: ${jooqJdbcUrl}
    username: ${jooqJdbcUser}
    password: ${jooqJdbcPassword}
    hikari:
      schema: ${schema}
  jooq:
    sql-dialect: postgres

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: ${app.management.base-path:/actuator}
    enabled-by-default: true
  server:
    servlet:
      context-path: ${app.management.base-path:/actuator}