server:
  port: 9999

spring:
  application:
    name: dennis-light-step-demo
  datasource:
    url: ${jooqJdbcUrl}
    username: ${jooqJdbcUser}
    password: ${jooqJdbcPassword}
    hikari:
      schema: ${schema}
  jooq:
    sql-dialect: postgres